//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AluminiumShutter
    {
        public int ID { get; set; }
        public Nullable<int> COL_1 { get; set; }
        public Nullable<int> COL_2 { get; set; }
        public Nullable<int> COL_3 { get; set; }
        public Nullable<int> COL_4 { get; set; }
        public Nullable<int> COL_5 { get; set; }
        public Nullable<int> COL_6 { get; set; }
        public Nullable<int> COL_7 { get; set; }
        public Nullable<int> COL_8 { get; set; }
        public Nullable<int> COL_9 { get; set; }
        public Nullable<int> COL_10 { get; set; }
        public Nullable<int> COL_11 { get; set; }
        public Nullable<int> COL_12 { get; set; }
        public Nullable<int> COL_13 { get; set; }
        public Nullable<int> COL_14 { get; set; }
        public Nullable<int> COL_15 { get; set; }
        public Nullable<int> COL_16 { get; set; }
        public Nullable<int> COL_17 { get; set; }
        public Nullable<int> COL_18 { get; set; }
    }
}
