//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AppAccess
    {
        public int ID { get; set; }
        public int GrantAccess { get; set; }
        public string Name { get; set; }
        public string QuoteID { get; set; }
        public Nullable<bool> Current { get; set; }
        public string Mobile { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string QSyncAccess { get; set; }
        public string userEmail { get; set; }
        public Nullable<int> ChangePW { get; set; }
    }
}
