//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class BuildChanx
    {
        public int ID { get; set; }
        public string MMBR { get; set; }
        public string New_MMBR { get; set; }
        public string AppliedChanges { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> VersionReleaseDate { get; set; }
        public Nullable<int> ReleaseComplete { get; set; }
    }
}
