//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class C06mm
    {
        public int ID { get; set; }
        public Nullable<decimal> COL_1 { get; set; }
        public Nullable<int> COL_2 { get; set; }
        public Nullable<int> COL_3 { get; set; }
        public Nullable<int> COL_4 { get; set; }
        public Nullable<int> COL_5 { get; set; }
        public Nullable<int> COL_6 { get; set; }
        public Nullable<int> COL_7 { get; set; }
        public string COL_8 { get; set; }
        public string COL_9 { get; set; }
    }
}
