//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class customermaster
    {
        public int MasterID { get; set; }
        public string CompCust { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PC { get; set; }
        public string MainPh { get; set; }
        public string MainFax { get; set; }
        public string MainMob { get; set; }
        public string MainEmail { get; set; }
        public bool Current { get; set; }
    }
}
