//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class customercontmaster
    {
        public int MasterCC { get; set; }
        public int MCID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Phone { get; set; }
        public string Mob { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Current { get; set; }
    }
}
