//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invitems = new ObservableCollection<invitem>();
        }
    
        public int InvoiceNumber { get; set; }
        public Nullable<int> OrigInvNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerOrderNo { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string AccountNo { get; set; }
        public string CompCust { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string SAddress { get; set; }
        public string SSuburb { get; set; }
        public string SState { get; set; }
        public string SPostCode { get; set; }
        public string Comments { get; set; }
        public string InvCode { get; set; }
        public string CustEmail { get; set; }
        public string User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<invitem> invitems { get; set; }
    }
}
