//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class message
    {
        public int MsgID { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public string MsgPriority { get; set; }
        public string Heading { get; set; }
        public string Message1 { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int Hide { get; set; }
    }
}
