//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class nswpc
    {
        public int ID { get; set; }
        public Nullable<double> Pcode { get; set; }
        public string Locality { get; set; }
        public string State { get; set; }
        public string Comments { get; set; }
        public string Category { get; set; }
    }
}
