//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class QuoteDateCorrection
    {
        public int QuoteNumber { get; set; }
        public string Representative { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public System.DateTime ModifyStamp { get; set; }
    }
}
