//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class shuttersheet
    {
        public int ID { get; set; }
        public int QuoteID { get; set; }
        public int ContMasterID { get; set; }
        public Nullable<double> JobNumber { get; set; }
        public string JobNumber2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerName { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Order_Number { get; set; }
        public string Standard { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Centre { get; set; }
        public string Springs { get; set; }
        public string SlatSize { get; set; }
        public Nullable<double> Gauge { get; set; }
        public string Collars { get; set; }
        public string RevMount { get; set; }
        public string WireByAble { get; set; }
        public Nullable<double> FixingType { get; set; }
        public Nullable<double> BottomRail { get; set; }
        public Nullable<double> Drive { get; set; }
        public Nullable<double> Finish { get; set; }
        public Nullable<double> Hand { get; set; }
        public Nullable<bool> CapRight { get; set; }
        public Nullable<bool> CapLeft { get; set; }
        public string Windlock { get; set; }
        public string TrackSize { get; set; }
        public Nullable<double> DriveFixing { get; set; }
        public string Options1 { get; set; }
        public string Options2 { get; set; }
        public string Options3 { get; set; }
        public string Options4 { get; set; }
        public string Options5 { get; set; }
        public string Colour { get; set; }
    }
}
