//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site()
        {
            this.services = new ObservableCollection<service>();
        }
    
        public int CustNo { get; set; }
        public int SiteNo { get; set; }
        public string SiteName { get; set; }
        public string SiteContact { get; set; }
        public string Address { get; set; }
        public Nullable<int> Suburb { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string InstallRefNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> ServiceCustomer { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public string NextServiceDate { get; set; }
        public string C3MonthSvc { get; set; }
        public string C6MonthSvc { get; set; }
        public string YearlyService { get; set; }
        public string SingleService { get; set; }
        public string ConfirmService { get; set; }
        public Nullable<double> Price { get; set; }
        public string MapRef { get; set; }
        public string AcctCust { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<service> services { get; set; }
    }
}
