//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tandc
    {
        public int id { get; set; }
        public Nullable<int> lineNum { get; set; }
        public string terms { get; set; }
        public Nullable<int> active { get; set; }
        public string mod_Stamp { get; set; }
    }
}
