//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class variable
    {
        public int id { get; set; }
        public string gtype { get; set; }
        public string Item { get; set; }
        public string StorageItem { get; set; }
        public string Active { get; set; }
    }
}
