//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=abledoors.net.au;user id=abab1199_qadacc;password=@mjK%U5eyNOK;persistsecu" +
            "rityinfo=True;database=abab1199_qsync")]
        public string dbconnect {
            get {
                return ((string)(this["dbconnect"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Level")]
        public string Accesslevel {
            get {
                return ((string)(this["Accesslevel"]));
            }
            set {
                this["Accesslevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ID")]
        public string Qid {
            get {
                return ((string)(this["Qid"]));
            }
            set {
                this["Qid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@abledoors.com.au")]
        public string MyUser {
            get {
                return ((string)(this["MyUser"]));
            }
            set {
                this["MyUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("this is why craig@youritlink.com.au")]
        public string userEmail {
            get {
                return ((string)(this["userEmail"]));
            }
            set {
                this["userEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("this is why WPT$Matrix4390")]
        public string userPW {
            get {
                return ((string)(this["userPW"]));
            }
            set {
                this["userPW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("this is why smtp.office365.com")]
        public string userSMTP {
            get {
                return ((string)(this["userSMTP"]));
            }
            set {
                this["userSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int userSMTPPort {
            get {
                return ((int)(this["userSMTPPort"]));
            }
            set {
                this["userSMTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not in use")]
        public string userReplyTo {
            get {
                return ((string)(this["userReplyTo"]));
            }
            set {
                this["userReplyTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User")]
        public string emailUsed {
            get {
                return ((string)(this["emailUsed"]));
            }
            set {
                this["emailUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int redLoad {
            get {
                return ((int)(this["redLoad"]));
            }
            set {
                this["redLoad"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=abledoors.net.au;user id=abab1199_qadacc;password=@mjK%U5eyNOK;convert zer" +
            "o datetime=True;persistsecurityinfo=True;database=abab1199_qsync")]
        public string QSyncReportsConnection {
            get {
                return ((string)(this["QSyncReportsConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=abledoors.net.au;user id=abab1199_qadacc;password=@mjK%U5eyNOK;database=ab" +
            "ab1199_qsync;convert zero datetime=True;persistsecurityinfo=True")]
        public string abab1199_qsyncConnectionString {
            get {
                return ((string)(this["abab1199_qsyncConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\QSync\\Templates\\")]
        public string ReportsFolder {
            get {
                return ((string)(this["ReportsFolder"]));
            }
            set {
                this["ReportsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\QSync\\")]
        public string TempReportsFolder {
            get {
                return ((string)(this["TempReportsFolder"]));
            }
            set {
                this["TempReportsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to QSync | For Support Call 0410 669 634 | QSync  by Your IT Link")]
        public string Status {
            get {
                return ((string)(this["Status"]));
            }
            set {
                this["Status"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Resources/favicon.ico")]
        public string Icon {
            get {
                return ((string)(this["Icon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\QSync\\Backup\\")]
        public string DBBacukup {
            get {
                return ((string)(this["DBBacukup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=abledoors.net.au;user id=abab1199_qadacc;password=@mjK%U5eyNOK;convert zer" +
            "o datetime=True;database=abab1199_qsync;charset=utf8")]
        public string DBBackupConn {
            get {
                return ((string)(this["DBBackupConn"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.4")]
        public string ReportsVersion {
            get {
                return ((string)(this["ReportsVersion"]));
            }
            set {
                this["ReportsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QSync V4.0.1.30")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Hi,

Thank you for your time today! Please find attached a quotation for works required / requested for your premises. 
If you wish to go ahead with the quotation please complete the attached ""QuoteAcceptance.pdf"" document and send either via email to: doorservice@abledoors.com.au or via fax on: 02-9757-1652.

If you have any questions or concerns, please do not hesitate to contact us.

Regards,

Craig McEwen
Able Door Services (NSW) Pty Ltd
24 Hours Emergency Service
Ph: 02 9757-1877
www.abledoors.com.au")]
        public string stdEmailTemplate {
            get {
                return ((string)(this["stdEmailTemplate"]));
            }
            set {
                this["stdEmailTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Hi,

Thank you for your time today! Please find attached a quotation for works required / requested for your premises. 
If you wish to go ahead with the quotation please complete the attached ""QuoteAcceptance.pdf"" document and send either via email to: doorservice@abledoors.com.au or via fax on: 02-9757-1652.

If you have any questions or concerns, please do not hesitate to contact us.

Regards,

Craig McEwen
Able Door Services (NSW) Pty Ltd
24 Hours Emergency Service
Ph: 02 9757-1877
www.abledoors.com.au")]
        public string customEmailTemplate {
            get {
                return ((string)(this["customEmailTemplate"]));
            }
            set {
                this["customEmailTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PMR-V4.0")]
        public string PMR {
            get {
                return ((string)(this["PMR"]));
            }
            set {
                this["PMR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INV-V4.0")]
        public string INV {
            get {
                return ((string)(this["INV"]));
            }
            set {
                this["INV"] = value;
            }
        }
    }
}
